In [1]:
import numpy as np
import pandas as pd
import requests

In [2]:
inat= pd.read_csv('inatchorap_python.csv')

In [6]:
inat.head()

,gbifID,class,order,family,genus,species,verbatimScientificName,countryCode,stateProvince,decimalLatitude,decimalLongitude,coordinateUncertaintyInMeters,eventDate,day,month,year,taxonKey,identifiedBy,rightsHolder
0,2814250707,Amphibia,Anura,Bufonidae,Anaxyrus,Anaxyrus americanus,Anaxyrus americanus,US,Vermont,44.612382,-72.357086,73.0,2020-07-03T08:32:55,3,7,2020,2422872,nickdunham,Michael Tessler
1,2823164392,Squamata,NaN,Colubridae,Diadophis,Diadophis punctatus,Diadophis punctatus,US,Alabama,34.674185,-86.518286,6.0,2020-07-22T12:00:03,22,7,2020,8763701,Matt,tcpremo
2,3109128330,Testudines,NaN,Emydidae,Chrysemys,Chrysemys picta,Chrysemys picta,US,Vermont,43.645870,-72.404306,361.0,2021-04-27T17:35:00,27,4,2021,2443133,Nancy,Nancy
3,3113357158,Aves,Passeriformes,Cardinalidae,Pheucticus,Pheucticus ludovicianus,Pheucticus ludovicianus,US,New York,41.352048,-74.495587,27816.0,2021-05-08T22:13:00,8,5,2021,2490494,mayessj,mayessj
4,3117884668,Aves,Passeriformes,Cardinalidae,Piranga,Piranga olivacea,Piranga olivacea,US,Virginia,37.283050,-80.468273,2.0,2021-05-14T08:07:00,14,5,2021,2488517,Cyrus Li,Cyrus Li

In [7]:
inat.isnull().sum().sort_values(ascending = False)

coordinateUncertaintyInMeters    105304
order                             81671
class                             21646
species                            4024
identifiedBy                       3214
genus                               218
stateProvince                         3
gbifID                                0
day                                   0
taxonKey                              0
year                                  0
month                                 0
decimalLatitude                       0
eventDate                             0
decimalLongitude                      0
countryCode                           0
verbatimScientificName                0
family                                0
rightsHolder                          0
dtype: int64

In [3]:
inat.dropna(subset= ['stateProvince'], inplace = True)

In [4]:
inat.isnull().sum().sort_values(ascending = False)

coordinateUncertaintyInMeters    105304
order                             81671
class                             21646
species                            4024
identifiedBy                       3214
genus                               218
gbifID                                0
eventDate                             0
taxonKey                              0
year                                  0
month                                 0
day                                   0
decimalLatitude                       0
decimalLongitude                      0
stateProvince                         0
countryCode                           0
verbatimScientificName                0
family                                0
rightsHolder                          0
dtype: int64

In [10]:
inat['species'].isnull()

0         False
1         False
2         False
3         False
4         False
          ...
725791    False
725792    False
725793    False
725794    False
725795    False
Name: species, Length: 725793, dtype: bool

In [11]:
inat[inat['species'].isna()]

,gbifID,class,order,family,genus,species,verbatimScientificName,countryCode,stateProvince,decimalLatitude,decimalLongitude,coordinateUncertaintyInMeters,eventDate,day,month,year,taxonKey,identifiedBy,rightsHolder
37,1562976504,Amphibia,Caudata,Plethodontidae,Desmognathus,NaN,Desmognathus gvnigeusgwotli,US,Tennessee,35.687667,-83.537995,NaN,2017-05-23T11:37:11,23,5,2017,2431198,Josh,Josh
79,3915501505,Amphibia,Caudata,Plethodontidae,Desmognathus,NaN,Desmognathus kanawha,US,Virginia,36.806289,-80.355094,54.0,2022-04-17T09:36:42,17,4,2022,2431198,Ty Smith,alanna-belmont
692,1848763466,Mammalia,Carnivora,Mustelidae,Mustela,NaN,Neogale frenata,US,Alabama,34.748987,-86.145991,28790.0,2018-05-27T19:41:50,27,5,2018,4833733,Helen A. Czech,Helen A. Czech
747,1949981691,Mammalia,Rodentia,Sciuridae,Glaucomys,NaN,Glaucomys,US,Vermont,43.985458,-72.886663,27411.0,2017-11-22T04:04:00,22,11,2017,2437330,wtobin,wtobin
861,3466071715,Aves,Anseriformes,Anatidae,NaN,NaN,Anas platyrhynchos × Cairina moschata,CA,Nova Scotia,44.673445,-63.563363,2.0,2022-01-23T16:38:00,23,1,2022,2986,greenari,greenari
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
724823,1838361473,Aves,Anseriformes,Anatidae,Anas,NaN,Anas rubripes × platyrhynchos,US,Vermont,44.192171,-72.587767,1893.0,2018-04-02T14:59:00,2,4,2018,2498056,Joshua Lincoln,Joshua Lincoln
725309,2826430539,Amphibia,Caudata,Plethodontidae,Desmognathus,NaN,Desmognathus gvnigeusgwotli,US,Tennessee,35.510385,-83.917920,28677.0,2020-07-24T11:11:00,24,7,2020,2431198,Todd W. Pierson,Trevor Slovick
725730,3108985611,Mammalia,Carnivora,Mustelidae,Mustela,NaN,Neogale vison,US,New York,42.458872,-76.505394,19.0,2021-04-23T20:14:12,23,4,2021,4833733,serenvillwock,serenvillwock
725745,2366159447,Mammalia,Chiroptera,Vespertilionidae,Myotis,NaN,Myotis,US,New York,42.462786,-76.431931,27630.0,2008-05-20T13:17:00,20,5,2008,2432384,bryanto,Nicholas Sly
725752,2634422687,Mammalia,Carnivora,Mustelidae,Mustela,NaN,Neogale vison,US,Vermont,43.488931,-72.392248,24.0,2020-05-31T09:10:00,31,5,2020,4833733,er-birds,er-birds

In [12]:
inat.shape

(725793, 19)

In [5]:
Sciname = inat['verbatimScientificName'].unique()

In [17]:
Sciname.shape

(1685,)

In [14]:
type(Sciname)

numpy.ndarray

In [6]:
sciname = list(Sciname)

In [16]:
type(sciname)

list

In [7]:
from bs4 import BeautifulSoup as soup

In [8]:
import time

In [10]:
Common_name = []

for species in sciname:
    wiki_url = 'https://en.wikipedia.org/wiki/'+species
    name = requests.get(wiki_url).text
    name_soup = soup(name, 'html.parser')
    com_name = name_soup.select('title')[0].text[:-12]
    Common_name.append(com_name)

    time.sleep(.1)

In [11]:
Common_name

['American toad',
 'Ring-necked snake',
 'Painted turtle',
 'Rose-breasted grosbeak',
 'Scarlet tanager',
 'American bullfrog',
 'Eastern newt',
 'Dickcissel',
 'White-tailed deer',
 'Gray catbird',
 'Milk snake',
 'Wood duck',
 'Chipping sparrow',
 'Bluegill',
 'Mourning dove',
 'Sharp-shinned hawk',
 'Common starling',
 'Common snapping turtle',
 'Eastern cottontail',
 'Pantherophis alleghaniensis',
 'Ruby-crowned kinglet',
 'American black duck',
 'Northern slimy salamander',
 'Eastern phoebe',
 'Purple finch',
 'Wild turkey',
 'Merlin (bird)',
 'Tree swallow',
 'Northern mockingbird',
 'Spring peeper',
 'Mallard',
 'Spotted-tail salamander',
 'Desmognathus gvnigeusgwotli',
 'Eastern chipmunk',
 'Agkistrodon piscivorus',
 'House sparrow',
 'Ruby-throated hummingbird',
 'House finch',
 'Black-bellied whistling duck',
 'Wood frog',
 'Great egret',
 'Yellow-rumped warbler',
 'Hairy woodpecker',
 'Red-tailed hawk',
 'Cape May warbler',
 'Red-winged blackbird',
 'Common garter snake',
 'Southern red-backed vole',
 'Common watersnake',
 'Red-backed salamander',
 'Fantail darter',
 'Rough-legged buzzard',
 'Carolina wren',
 "DeKay's brown snake",
 'Pileated woodpecker',
 'Northern cardinal',
 'Eastern kingbird',
 'Canada goose',
 'Eastern fence lizard',
 'Black-and-white warbler',
 'Song sparrow',
 'American yellow warbler',
 'Black vulture',
 'Desmognathus kanawha',
 'Queen snake',
 'Bufflehead',
 'American black bear',
 'Fisher (animal)',
 'Killdeer',
 'Black-capped chickadee',
 'North American beaver',
 'Dog',
 'Spring salamander',
 'American red squirrel',
 'Carolina chickadee',
 'Eastern bluebird',
 'Red-headed woodpecker',
 'Lithobates clamitans',
 'Eastern gray squirrel',
 'Painted turtle',
 'Pickerel frog',
 'Eastern garter snake',
 'Barred owl',
 'American goldfinch',
 'Field sparrow',
 'Yellow-bellied slider',
 'Spotted salamander',
 'Common pheasant',
 'Northern leopard frog',
 'Yellow perch',
 'Tufted titmouse',
 'Barn swallow',
 'Timber rattlesnake',
 'Gyrinophilus porphyriticus danielsi',
 'Yellow-bellied sapsucker',
 'American robin',
 'Coyote',
 'Eastern box turtle',
 'Wood thrush',
 'Stilt sandpiper',
 'Ivory gull',
 'Anolis carolinensis',
 'Mute swan',
 'Carphophis amoenus',
 'Shenandoah salamander',
 'Ardea herodias occidentalis',
 'Dark-eyed junco',
 'Eastern worm snake',
 'Greater yellowlegs',
 'American woodcock',
 'Indigo bunting',
 'Rainbow darter',
 'Great blue heron',
 'Mourning warbler',
 'Blue jay',
 'Redear sunfish',
 'North American porcupine',
 'Eastern copperhead',
 'Northern flicker',
 'Goldfish',
 'Desmognathus fuscus',
 'Valley and ridge salamander',
 'Turkey vulture',
 'White-breasted nuthatch',
 'Pied-billed grebe',
 'Nashville warbler',
 'Eastern towhee',
 'Virginia big-eared bat',
 'Cedar waxwing',
 'Redhead (bird)',
 'Blue-spotted salamander',
 'Virginia opossum',
 'Purple martin',
 'American wigeon',
 'Blackburnian warbler',
 'Fox sparrow',
 'Hooded merganser',
 'Red fox',
 'Blue grosbeak',
 'Belted kingfisher',
 'European herring gull',
 'Brown-headed cowbird',
 'Eastern newt',
 'White shiner',
 'Pond slider',
 'Haemorhous purpureus purpureus',
 'Spotted sandpiper',
 'White-throated sparrow',
 'Downy woodpecker',
 'Smooth green snake',
 'Hooded warbler',
 'Allegheny Mountain dusky salamander',
 "Harris's sparrow",
 'Red-breasted nuthatch',
 'Northern rough-winged swallow',
 'Bald eagle',
 'Red-bellied woodpecker',
 'Painted turtle',
 'Ovenbird',
 'Gray treefrog',
 'Muskrat',
 'North American river otter',
 'Common box turtle',
 'Elk',
 'Brown creeper',
 'Thryothorus ludovicianus ludovicianus',
 'Groundhog',
 'Common grackle',
 'Domestic duck',
 'Pseudotriton ruber ruber',
 'Red-shouldered hawk',
 'Eastern mud turtle',
 'American redstart',
 'Northern shoveler',
 'Red salamander',
 'Lampropeltis getula',
 'Broad-winged hawk',
 'Raccoon',
 'Common redpoll',
 'Black-throated blue warbler',
 'Blackpoll warbler',
 'American kestrel',
 'Sternotherus odoratus',
 'Common raven',
 'Osprey',
 'Mottled sculpin',
 'Hermit thrush',
 'Longnose dace',
 'Jefferson salamander',
 'Eurycea longicauda',
 'Bohemian waxwing',
 "Cooper's hawk",
 'Common loon',
 'Brown thrasher',
 'Baltimore oriole',
 'Anaxyrus americanus americanus',
 'Pumpkinseed',
 'Striped skunk',
 'Brown trout',
 'Bronze darter',
 'Yellow-billed cuckoo',
 'Common yellowthroat',
 'Veery',
 'Upland sandpiper',
 'Blue-headed vireo',
 'Green heron',
 'Smallmouth bass',
 'Fox squirrel',
 'Northern harrier',
 'American green tree frog',
 'Common watersnake',
 'Warbling vireo',
 'Chestnut-sided warbler',
 'Grasshopper sparrow',
 'Plestiodon fasciatus',
 'Common merganser',
 'Solitary sandpiper',
 'Golden-winged warbler',
 'Canada warbler',
 'Northern saw-whet owl',
 'Gray ratsnake',
 'Cheat Mountain salamander',
 'Storeria occipitomaculata',
 'Pipilo erythrophthalmus erythrophthalmus',
 'Pine warbler',
 'Spotted dusky salamander',
 'Semipalmated plover',
 'Wood turtle',
 'Northern waterthrush',
 'Cliff swallow',
 'American crow',
 'Red-breasted merganser',
 'Upland chorus frog',
 'White-spotted slimy salamander',
 'White sucker',
 'Squirrel tree frog',
 'Eastern deer mouse',
 'Etheostoma rufilineatum',
 'Swamp sparrow',
 'Moose',
 'Glaucous gull',
 'Double-crested cormorant',
 'Gadwall',
 'Largemouth bass',
 'Worm-eating warbler',
 'Long-tailed weasel',
 'Ring-billed gull',
 'House wren',
 'Cathartes aura septentrionalis',
 'Southern leopard frog',
 'Coragyps atratus atratus',
 "Swainson's thrush",
 'Brown-headed nuthatch',
 'Loggerhead shrike',
 'Eastern racer',
 'New World flying squirrel',
 'Red-eyed vireo',
 'Northern pintail',
 'Great black-backed gull',
 'Rainbow trout',
 'Northern gray-cheeked salamander',
 'Brown rat',
 'Savannah sparrow',
 'Prothonotary warbler',
 'Four-toed salamander',
 'Northern short-tailed shrew',
 'Northern map turtle',
 'Eastern meadow vole',
 'Eastern mosquitofish',
 'Domestic pigeon',
 'Three-lined salamander',
 'Setophaga coronata coronata',
 'Peregrine falcon',
 'Imitator salamander',
 'Anas platyrhynchos × Cairina moschata',
 'Anser caerulescens atlanticus',
 'Great horned owl',
 'Southern flying squirrel',
 'Black guillemot',
 'Blue-gray gnatcatcher',
 'Dryophytes gratiosus',
 'Mandarin duck',
 'Palm warbler',
 'Anaxyrus fowleri',
 'Snow bunting',
 'Pine grosbeak',
 'Black-backed woodpecker',
 'Least flycatcher',
 'Harlequin duck',
 'American white pelican',
 "Wilson's warbler",
 'White-crowned sparrow',
 'Golden eagle',
 'Ribbon snake',
 'Redbreast sunfish',
 'Ruddy duck',
 'Yellowfin shiner',
 'Desmognathus amphileucus',
 'Snowshoe hare',
 'Chimney swift',
 "Wilson's snipe",
 'Common goldeneye',
 'Brook trout',
 'American alligator',
 'Golden-crowned kinglet',
 'Black crappie',
 'Banded killifish',
 'American tree sparrow',
 "Bonaparte's gull",
 'Evening grosbeak',
 "Cope's gray treefrog",
 'Northern two-lined salamander',
 'Magnolia warbler',
 'Lampropeltis nigra',
 'Eastern meadowlark',
 'Domestic Muscovy duck',
 'Didelphis virginiana virginiana',
 'Canada jay',
 'Northern parula',
 'Western blacknose dace',
 'Big brown bat',
 'White-winged scoter',
 'Eastern screech owl',
 'Fish crow',
 'Mountain redbelly dace',
 'Kentucky warbler',
 'Mediterranean house gecko',
 'Louisiana waterthrush',
 'White-eyed vireo',
 'Least sandpiper',
 'Swan goose',
 'Southern red-backed salamander',
 'Etheostoma zonale',
 'Opheodrys aestivus',
 'Northern bobwhite',
 "Wehrle's salamander",
 'Eurasian collared dove',
 'Golden shiner',
 'American mink',
 'Sternotherus peltifer',
 'Bay-breasted warbler',
 'Rock dove',
 'Northern cricket frog',
 'Bobcat',
 'Peromyscus',
 'Noturus insignis',
 'Pandion haliaetus carolinensis',
 'Tricolored bat',
 'Southern two-lined salamander',
 'Bobolink',
 'Common gallinule',
 'Micropterus tallapoosae',
 'Blue Ridge dusky salamander',
 'Greenside darter',
 'Diadophis punctatus edwardsii',
 'Gilt darter',
 'Great crested flycatcher',
 'Seal salamander',
 'Corn snake',
 'Nerodia erythrogaster',
 'Eastern red bat',
 'Plestiodon laticeps',
 'Tennessee warbler',
 'Barnacle goose',
 'Winter wren',
 'Yellow-bellied flycatcher',
 'Micropterus chattahoochae',
 'Snubnose darter',
 'Yellow-breasted chat',
 'Summer tanager',
 'Snowy owl',
 'North American least shrew',
 'Acadian flycatcher',
 'Laughing gull',
 'Pine siskin',
 'Red crossbill',
 'Junco hyemalis hyemalis',
 'Eastern whip-poor-will',
 'Green salamander',
 'Greater white-fronted goose',
 'Glossy ibis',
 'Horned grebe',
 "Henslow's sparrow",
 'Black scoter',
 'Nine-banded armadillo',
 'Orchard oriole',
 'Scissor-tailed flycatcher',
 'Scincella lateralis',
 'Bluehead chub',
 'Blue Ridge two-lined salamander',
 'Anas rubripes × platyrhynchos',
 'Clay-colored sparrow',
 'Long-tailed duck',
 'Barn owl',
 'Northern shrike',
 'American coot',
 'Diadophis punctatus punctatus',
 'Cat',
 'Haemorhous mexicanus frontalis',
 'Colaptes auratus auratus',
 'Lesser black-backed gull',
 'Thamnophis sirtalis pallidulus',
 'Eurasian teal',
 'Nerodia sipedon pleuralis',
 'Thick-billed murre',
 'Ammodytes',
 'Carolina mountain dusky salamander',
 'Smooth earth snake',
 'Prairie warbler',
 'Fallfish',
 'Blue Ridge gray-cheeked salamander',
 'Poecile atricapillus atricapillus',
 'Wild turkey',
 'Southern painted turtle',
 'Winter skate',
 'Blue-winged warbler',
 'Passer domesticus domesticus',
 'Gray fox',
 'Green sunfish',
 'Ruffed grouse',
 'Plethodon chattahoochee',
 'Mourning dove',
 'Rock bass',
 'Roseate spoonbill',
 'Striped shiner',
 'Ambystoma talpoideum',
 'Thamnophis saurita saurita',
 'Common nighthawk',
 'Semotilus atromaculatus',
 'Black-billed cuckoo',
 'Spiny softshell turtle',
 'Rosyside dace',
 'Short-eared owl',
 'Snow goose',
 'Star-nosed mole',
 'Six-lined racerunner',
 'Channel catfish',
 'Eastern spotted skunk',
 'Two-barred crossbill',
 'Haldea',
 'Bluebreast darter',
 'Desmognathus perlapsus',
 'Eastern blacknose dace',
 'American black bear',
 'Yonahlossee salamander',
 'Black-throated green warbler',
 'Common tern',
 'Ring-necked duck',
 'Philadelphia vireo',
 'River cooter',
 'Pigeon Mountain salamander',
 'Blue-winged teal',
 'Olive-sided flycatcher',
 'Desmognathus mavrokoilius',
 'Tufted duck',
 'Deirochelyinae',
 'Shorthead garter snake',
 'Cinereus shrew',
 'Empidonax',
 'Marbled salamander',
 'Lampropeltis rhombomaculata',
 'Walleye',
 'Trumpeter swan',
 "Weller's salamander",
 'Lapland longspur',
 'Chain pickerel',
 'Mobile logperch',
 'Red-eared slider',
 'Melopsittacus undulatus (domestic type)',
 'Lake trout',
 'Sora (bird)',
 'Northern redbelly dace',
 'Lesser scaup',
 'Sandhill crane',
 'Common shiner',
 'Red-throated loon',
 'American red fox',
 'Northern hogsucker',
 'Vermivora chrysoptera × cyanoptera',
 'Semipalmated sandpiper',
 'Lesser yellowlegs',
 'Malaclemys terrapin terrapin',
 'Brown bullhead',
 'Southeastern crown snake',
 'Eurasian carp',
 'American bittern',
 'Buff-bellied pipit',
 'Cyprinella spiloptera',
 'Sand martin',
 'Sockeye salmon',
 'Blackbanded darter',
 'Northern red-bellied cooter',
 'Northern goshawk',
 'Lithobates sphenocephalus utricularius',
 'Wounded darter',
 'Micropterus henshalli',
 'Colaptes auratus luteus',
 'Northern pygmy salamander',
 'Northern zigzag salamander',
 'Blackside dace',
 'Peaks of Otter salamander',
 "Ross's goose",
 'Central stoneroller',
 'White-footed mouse',
 'Eastern red-tailed hawk',
 'Eastern wood pewee',
 'Southern redbelly dace',
 'American ermine',
 'Warpaint shiner',
 'Gyrinophilus porphyriticus porphyriticus',
 'Red knot',
 'Southern brook lamprey',
 'Eastern river cooter',
 'Flathead catfish',
 'Northern snakehead',
 'Red-necked grebe',
 'Vesper sparrow',
 'Greater scaup',
 'Polioptila caerulea caerulea',
 'Northern black racer',
 'Black-crowned night heron',
 'Flat-headed salamander',
 'Cerulean warbler',
 'Shenandoah Mountain salamander',
 'Haliaeetus leucocephalus washingtoniensis',
 'Mistle thrush',
 'Rusty blackbird',
 'Willet',
 'Setophaga palmarum hypochrysea',
 'Northern hawk-owl',
 'Brook silverside',
 'Lake chubsucker',
 'Cackling goose',
 'American eel',
 'Sedge wren',
 'Setophaga palmarum palmarum',
 'Swallowtail shiner',
 'Southern toad',
 'Grass carp',
 'Brook stickleback',
 'Ciona intestinalis',
 'Ruff (bird)',
 'Anhinga',
 'Northern redbelly snake',
 'Spruce grouse',
 'Strix varia varia',
 'Longjaw minnow',
 'Ocoee salamander',
 "Bicknell's thrush",
 'Longear sunfish',
 'Gastrophryne carolinensis',
 'Golden topminnow',
 'American golden plover',
 'Canada lynx',
 'Warmouth',
 'Yellow-throated warbler',
 'Dixie Cavern salamander',
 'Dunlin',
 'Aspidoscelis sexlineatus sexlineatus',
 'Desmognathus adatsihi',
 'Southern studfish',
 'Red-cheeked salamander',
 'Junco hyemalis carolinensis',
 'Blacktail redhorse',
 'Tundra bean goose',
 'Tallapoosa sculpin',
 'Seepage salamander',
 "Townsend's solitaire",
 'Marsh wren',
 'Corvus',
 'Pectoral sandpiper',
 'Ravine salamander',
 'Spotted turtle',
 'Eastern elk',
 'Anser anser × Branta canadensis',
 'Whooping crane',
 'Bluntnose minnow',
 'Surf scoter',
 'Lark sparrow',
 'American pickerel',
 'Mexican free-tailed bat',
 'Yellow bullhead',
 'Ardea herodias herodias',
 'Macrhybopsis etnieri',
 'Northern flying squirrel',
 'Blacknose shiner',
 "Baird's sandpiper",
 'Greenbreast darter',
 'Mole salamander',
 'Swallow-tailed kite',
 "Lincoln's sparrow",
 'Wild boar',
 'Redspot darter',
 'Tundra swan',
 'Hairy-tailed mole',
 'Grey triggerfish',
 'Largescale stoneroller',
 'Long-eared owl',
 'Black tern',
 'Alder flycatcher',
 'Rainbow smelt',
 'Percina roanoka',
 'Longhorn sculpin',
 'Turdus migratorius migratorius',
 'Red-necked phalarope',
 'Mustelinae',
 'Grey plover',
 'Ruddy turnstone',
 'Greylag goose',
 'Chicken',
 'Southern gray-cheeked salamander',
 "Leach's storm petrel",
 'Spizella passerina passerina',
 "Ambystoma 'unisexual complex'",
 'Corvus corax principalis',
 'Black-knobbed map turtle',
 'Anser anser × cygnoides',
 'White-rumped sandpiper',
 'Horned lark',
 'Larus canus canus',
 'Northern gannet',
 'Woodland vole',
 'Escambia map turtle',
 'Brown booby',
 'Eastern hognose snake',
 'Cumberland Plateau salamander',
 'Blue Ridge sculpin',
 'Procyon lotor lotor',
 'Ameiurus platycephalus',
 'Botryllus schlosseri',
 'Ohio lamprey',
 'Atlantic salmon',
 'Opheodrys aestivus aestivus',
 'Bog turtle',
 'Horse',
 'Virginia rail',
 'Ardea alba egretta',
 'Orange-crowned warbler',
 'Brown pelican',
 'Canvasback',
 'Amia ocellicauda',
 'Yellow-spotted woodland salamander',
 "Swainson's hawk",
 'Yellow-crowned night heron',
 'Boreal chickadee',
 'Peregrine falcon',
 'House mouse',
 'Virginia valeriae valeriae',
 'Plestiodon',
 'Caspian tern',
 'Mosquitofish',
 'Mergus merganser americanus',
 'Common shelduck',
 'Lithobates',
 'Little auk',
 'Blacksburg salamander',
 'Green-winged teal',
 'Odocoileus virginianus virginianus',
 'Golden redhorse',
 'Meadow jumping mouse',
 'Varied thrush',
 'Longnose shiner',
 'Common eider',
 'Mink frog',
 'Short-billed dowitcher',
 'Lepomis gibbosus × cyanellus',
 'Spiny softshell turtle',
 'Ash-throated flycatcher',
 'Painted bunting',
 'Dwarf black-bellied salamander',
 'Western cattle egret',
 'Red fox sparrow',
 'Little blue heron',
 'Iceland gull',
 'Mississippi kite',
 'Willow flycatcher',
 'Fundulus olivaceus',
 'Arctic redpoll',
 'Pink-footed goose',
 'Red-legged salamander',
 'Redlip shiner',
 'Yellow-throated vireo',
 'Eurasian whimbrel',
 'American herring gull',
 'Virginia valeriae pulchra',
 'Sanderling',
 'Tennessee cave salamander',
 'Snowy egret',
 'Myotis septentrionalis',
 'Hemitripterus americanus',
 'Etheostoma duryi',
 'Common mudpuppy',
 'Empidonax traillii traillii',
 'Sandwich tern',
 'Nerodia rhombifer',
 'Northern studfish',
 'Gyrinophilus porphyriticus duryi',
 'Greengill sunfish',
 'Alewife (fish)',
 'Bull chub',
 'Giant Canada goose',
 'Atlantic puffin',
 'Tessellated darter',
 'Lark bunting',
 'Northern pike',
 'Southern Appalachian salamander',
 'Banded sculpin',
 'Egyptian goose',
 'Anas platyrhynchos × Mareca americana',
 'Mud snake',
 'Helmeted guineafowl',
 'Buteo',
 'Pseudotriton ruber schencki',
 'Eastern mole',
 'Longnose sucker',
 'Scaphiopus holbrookii',
 'Mummichog',
 'Plestiodon anthracinus',
 'Desmognathus',
 'Sitta carolinensis carolinensis',
 'Pygmy salamander',
 "Barrow's goldeneye",
 'Sauger',
 'Blacktail shiner',
 'Tricolor shiner',
 'Melospiza melodia melodia',
 'Marbled godwit',
 'River redhorse',
 'Grey-cheeked thrush',
 'Alabama map turtle',
 'Brant (goose)',
 'Mimic shiner',
 'Cyprinus rubrofuscus',
 'Telescope shiner',
 'South Mountain gray-cheeked salamander',
 'Boreal owl',
 'Whitetail shiner',
 'Anaxyrus',
 'Black-backed oriole',
 'Redeye bass',
 'Southeastern pocket gopher',
 'Big Levels salamander',
 'Tuskaloosa darter',
 'Rock gunnel',
 'Tennessee shiner',
 "Barbour's map turtle",
 'Alabama hog sucker',
 'Muscadine darter',
 'Odocoileus virginianus borealis',
 'Black redhorse',
 'Etheostoma osburni',
 'Longnose gar',
 'Lepomis macrochirus × microlophus',
 'Southern zigzag salamander',
 'Rosyface shiner',
 'Desmognathus balsameus',
 'Black swan',
 'Lake chub',
 'Corrugated darter',
 'Potomac sculpin',
 'Atlantic mackerel',
 'Hispid cotton rat',
 'Coyote',
 'Plestiodon anthracinus anthracinus',
 'Hellbender',
 'Sciurus niger niger',
 'Bucephala clangula × islandica',
 'Southern black racer',
 'Speckled darter',
 'Calidris',
 'Poecile hudsonicus littoralis',
 "Bullock's oriole",
 'Atlantic menhaden',
 'Great cormorant',
 'Eurasian wigeon',
 'Colubrinae',
 "Chuck-will's-widow",
 'Glassy darter',
 'Wood stork',
 'Parasitic jaeger',
 'Lake sturgeon',
 'Southeastern slimy salamander',
 'Fieryblack shiner',
 'Gyrinophilus palleucus palleucus',
 'Canada goose',
 "Bell's vireo",
 'American white ibis',
 'Round goby',
 'Myoxocephalus scorpius',
 'Eurycea longicauda longicauda',
 'Buff-breasted sandpiper',
 'Percina nevisensis',
 'Cumberland snubnose darter',
 'Pinicola enucleator leucura',
 'Chukar partridge',
 'Lepomis',
 'Plethodon',
 'Harbor seal',
 'Bonasa umbellus umbellus',
 'Poecile',
 'Mountain madtom',
 'Alces alces americana',
 'Plestiodon inexpectatus',
 'Lepomis cyanellus × gulosus',
 'Highscale shiner',
 'Fathead minnow',
 'Lepomis macrochirus purpurascens',
 'Freshwater drum',
 'Yellow bass',
 'American avocet',
 'Exoglossum maxillingua',
 'White-cheeked pintail',
 'Western kingbird',
 'Purple sandpiper',
 'Saffron shiner',
 'Black mountain salamander',
 'Snail bullhead',
 'Western meadowlark',
 'Percina westfalli',
 'Ondatra zibethicus zibethicus',
 'Black-chinned hummingbird',
 'Cumberland slider',
 'Sea lamprey',
 'Kentucky arrow darter',
 'Percina peltata',
 'King eider',
 'Pollachius virens',
 'Indian peafowl',
 'Black rat',
 'Flame chub',
 'Bubo virginianus virginianus',
 'Hyla',
 'Allegheny pearl dace',
 'Speckled madtom',
 'Least tern',
 "Blanding's turtle",
 'Cygnus columbianus columbianus',
 'Southern short-tailed shrew',
 "Thayer's gull",
 'Blackstripe topminnow',
 'Eastern glass lizard',
 'Allegheny woodrat',
 'Southern chorus frog',
 'River chub',
 'Swamp rabbit',
 'White bass',
 'Riverweed darter',
 'Domestic turkey',
 'Harbor seal',
 'Brownback salamander',
 'Woodland jumping mouse',
 'Etheostoma starnesi',
 'King rail',
 'Two-toed amphiuma',
 'Cyprinella eurystoma',
 'Kinosternon subrubrum hippocrepis',
 'Dryocopus pileatus abieticola',
 "Webster's salamander",
 'Hudsonian godwit',
 'Domestic guineafowl',
 'Smooth softshell turtle',
 'Least bittern',
 'Styela clava',
 'Alabama shiner',
 'Cheoah Bald salamander',
 'Dryobates pubescens medianus',
 'Smoky shrew',
 'Streamline chub',
 'Little brown bat',
 'Mud sunfish',
 "Swainson's warbler",
 'American gizzard shad',
 'White-winged dove',
 'Banded killifish',
 'Spotted bass',
 'Santeetlah dusky salamander',
 'Hirundo rustica erythrogaster',
 'Tamiasciurus hudsonicus gymnicus',
 'Pseudotriton montanus diastictus',
 'Microgadus tomcod',
 "Forster's tern",
 'Pseudotriton ruber nitidus',
 'Northern ravine salamander',
 'Spotted gar',

In [56]:
Common_name[:10]

['American toad',
 'Ring-necked snake',
 'Painted turtle',
 'Rose-breasted grosbeak',
 'Scarlet tanager',
 'American bullfrog',
 'Eastern newt',
 'Dickcissel',
 'White-tailed deer',
 'Gray catbird']

In [12]:
names = pd.DataFrame({'Scientific_name':sciname, 'Common_Name':Common_name})

In [13]:
names.head(4)

           Scientific_name             Common_Name
0      Anaxyrus americanus           American toad
1      Diadophis punctatus       Ring-necked snake
2          Chrysemys picta          Painted turtle
3  Pheucticus ludovicianus  Rose-breasted grosbeak

In [17]:
inat = inat.merge(names, how = 'left', left_on = 'verbatimScientificName', right_on = 'Scientific_name')

In [24]:
# Inat_complete = pd.merge(left = inat, right = names, how = 'left', left_on = 'verbatimScientificName', right_on = 'Scientific_name' )

In [18]:
inat.head()

,gbifID,class,order,family,genus,species,verbatimScientificName,countryCode,stateProvince,decimalLatitude,...,coordinateUncertaintyInMeters,eventDate,day,month,year,taxonKey,identifiedBy,rightsHolder,Scientific_name,Common_Name
0,2814250707,Amphibia,Anura,Bufonidae,Anaxyrus,Anaxyrus americanus,Anaxyrus americanus,US,Vermont,44.612382,...,73.0,2020-07-03T08:32:55,3,7,2020,2422872,nickdunham,Michael Tessler,Anaxyrus americanus,American toad
1,2823164392,Squamata,NaN,Colubridae,Diadophis,Diadophis punctatus,Diadophis punctatus,US,Alabama,34.674185,...,6.0,2020-07-22T12:00:03,22,7,2020,8763701,Matt,tcpremo,Diadophis punctatus,Ring-necked snake
2,3109128330,Testudines,NaN,Emydidae,Chrysemys,Chrysemys picta,Chrysemys picta,US,Vermont,43.645870,...,361.0,2021-04-27T17:35:00,27,4,2021,2443133,Nancy,Nancy,Chrysemys picta,Painted turtle
3,3113357158,Aves,Passeriformes,Cardinalidae,Pheucticus,Pheucticus ludovicianus,Pheucticus ludovicianus,US,New York,41.352048,...,27816.0,2021-05-08T22:13:00,8,5,2021,2490494,mayessj,mayessj,Pheucticus ludovicianus,Rose-breasted grosbeak
4,3117884668,Aves,Passeriformes,Cardinalidae,Piranga,Piranga olivacea,Piranga olivacea,US,Virginia,37.283050,...,2.0,2021-05-14T08:07:00,14,5,2021,2488517,Cyrus Li,Cyrus Li,Piranga olivacea,Scarlet tanager

In [20]:
type(inat)

pandas.core.frame.DataFrame

In [21]:
inat.to_csv('Inat.csv', index = False)